### ISSUE TITLE
Refactor the waveViewer code

### ISSUE THREAD

**Issue by kanhegaonkarsaurabh** [ListeningToWaves/musiscope-v2#19]
TODO: 

- [ ] Refactor the way buffer is accessed to accommodate totalRecording function with start and end time
- [ ] Remove the term 'len' and how it is used
- [ ] Refactor the state to use start and end

**Comment by frankyyzy** [comment]
- add back the lock feature
 - change get time data into get data

**Comment by frankyyzy** [comment]
should we close this?
